---
driver:
  name: vagrant
  require_chef_omnibus: 12.0.3
  customize:
    memory: 1024

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]

suites:
  - name: development
    run_list:
      - role[development]
